//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB120045_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aktovnosti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aktovnosti()
        {
            this.AktivnostiKomentari = new HashSet<AktivnostiKomentari>();
            this.AktivnostiKorisnici = new HashSet<AktivnostiKorisnici>();
            this.Ocjene = new HashSet<Ocjene>();
        }
    
        public int AktivnostID { get; set; }
        public string Naziv { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public byte[] Slika { get; set; }
        public byte[] SlikaThumb { get; set; }
        public Nullable<int> ZaposlenikID { get; set; }
        public string Ogranicenja { get; set; }
        public Nullable<int> VrstaAktivnostiID { get; set; }
        public Nullable<bool> Stalna { get; set; }
        public Nullable<System.TimeSpan> VrijemeAktivnosti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AktivnostiKomentari> AktivnostiKomentari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AktivnostiKorisnici> AktivnostiKorisnici { get; set; }
        public virtual VrstaAktivnosti VrstaAktivnosti { get; set; }
        public virtual Zaposlenici Zaposlenici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocjene> Ocjene { get; set; }
    }
}
