//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB120045_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnici()
        {
            this.AktivnostiKomentari = new HashSet<AktivnostiKomentari>();
            this.AktivnostiKorisnici = new HashSet<AktivnostiKorisnici>();
            this.Ocjene = new HashSet<Ocjene>();
            this.ZahtejviZaPrijavuUDom = new HashSet<ZahtejviZaPrijavuUDom>();
        }
    
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<System.DateTime> DatumRegistracije { get; set; }
        public string Grad { get; set; }
        public string Mail { get; set; }
        public Nullable<bool> StatusPrijave { get; set; }
        public string KorisnickoIme { get; set; }
        public string LozinkaSlt { get; set; }
        public string LozinkaHash { get; set; }
        public int KorisnikID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AktivnostiKomentari> AktivnostiKomentari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AktivnostiKorisnici> AktivnostiKorisnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocjene> Ocjene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZahtejviZaPrijavuUDom> ZahtejviZaPrijavuUDom { get; set; }
    }
}
