//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB120045_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacijenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacijenti()
        {
            this.Pregledi = new HashSet<Pregledi>();
            this.ZahtejviZaPrijavuUDom = new HashSet<ZahtejviZaPrijavuUDom>();
        }
    
        public int PacijentID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public string JMBG { get; set; }
        public System.DateTime DatumPrijave { get; set; }
        public int Skrbnici_SkrbnikID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> SpolID { get; set; }
        public Nullable<int> ZaposlenikID { get; set; }
        public Nullable<int> SobaID { get; set; }
    
        public virtual Skrbnici Skrbnici { get; set; }
        public virtual Sobe Sobe { get; set; }
        public virtual Spol Spol { get; set; }
        public virtual Zaposlenici Zaposlenici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregledi> Pregledi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZahtejviZaPrijavuUDom> ZahtejviZaPrijavuUDom { get; set; }
    }
}
