//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB120045_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sobe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sobe()
        {
            this.Pacijenti = new HashSet<Pacijenti>();
        }
    
        public int SobaID { get; set; }
        public Nullable<int> SpratID { get; set; }
        public Nullable<int> TipSobeID { get; set; }
        public Nullable<bool> slobodna { get; set; }
        public Nullable<int> BrojKreveta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pacijenti> Pacijenti { get; set; }
        public virtual Spratovi Spratovi { get; set; }
        public virtual TipoviSoba TipoviSoba { get; set; }
    }
}
